services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        POSTGRES_DB: warehouse
        POSTGRES_USER: warehouse
        POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: